[bdist_wheel]
universal = 1

[metadata]
license_file = LICENSE
license = GNU GPLv3 (or more recent equivalent)
author = Jonathan Peirce
author_email = jon.peirce@gmail.com
maintainer_email = jon.peirce@gmail.com
url = http://www.psychopy.org/
download_url = https://github.com/psychopy/psychopy/releases/
description = Psychology experiment software in Python
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 4 - Beta
    Operating System :: MacOS :: MacOS X
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 2
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7

[options]
python_requires = >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*
setup_requires = 
    distro; platform_system == "Linux"
install_requires =
    requests[security]==2.22.0
    numpy==1.18.1
    scipy==1.4.1
    matplotlib==3.3.0
    pandas==0.23.3
    pillow==7.2.0
    glfw==1.7.0
    pyopengl==3.1.0
    soundfile==0.10.2
    sounddevice==0.3.11
    python-bidi==0.4.0
    arabic_reshaper==2.0.14
    future==0.16.0
    json_tricks==3.12.2
    pyosf==1.0.5
    xlrd==1.1.0
    openpyxl==2.5.4
    pyserial==3.4
    pyyaml==3.13
    gevent==1.3.5
    msgpack==0.6.1
    msgpack-numpy==0.4.4.2
    psutil==5.4.6
    tables==3.4.4
    pyzmq==17.1.0
    moviepy==1.0.3
    opencv-python==3.4.2.17
    python-gitlab==1.5.1
    gitpython==2.1.11
    astunparse==1.5.0
    esprima==4.0.1
    freetype-py==2.0.0.post6
    jedi==0.17.2
    javascripthon==0.1.0
    pyglet==1.3.3
    questplus==2019.4
    imageio==2.5.0
    imageio-ffmpeg=0.2.0
    websocket_client==0.57.0
    pyqt5==5.11.3
    # Platform-specific dependencies.
    pyparallel==0.2.2; platform_system != "Darwin"
    pyWinhook==1.6.1; platform_system == "Windows"
    pyqmix==2018.12.13; platform_system == "Windows"
    pypiwin32==223; platform_system == "Windows"
    pyobjc-core==4.1; platform_system == "Darwin"
    pyobjc-framework-Quartz==4.1; platform_system == "Darwin"
    distro==1.5.0; platform_system == "Linux"

[options.entry_points]
gui_scripts =
    psychopy = psychopy.app.psychopyApp:main

[versioneer]
VCS = git
style = pep440
versionfile_source = psychopy/_version.py
versionfile_build =
tag_prefix = ''

[tool:pytest]
markers =
    needs_sound: requires sound hw, thus should not be excercised e.g. on travis-ci
    needs_pygame: requires pygame

